"""
NeuroBIDS-Flow — Train/Val/Test Splits Generator
=================================================
Generates reproducible train/val/test subject splits for benchmarking.
Saves splits as JSON — anyone who clones the repo gets identical splits.

Usage:
    python src/neurobids_flow/splits.py --bids-root ./bids_output
    python src/neurobids_flow/splits.py --bids-root ./bids_output --save splits.json
"""

from __future__ import annotations

import argparse
import json
import random
from pathlib import Path


def generate_splits(
    bids_root: str,
    train_ratio: float = 0.6,
    val_ratio: float = 0.2,
    test_ratio: float = 0.2,
    seed: int = 42,
) -> dict:
    """
    Auto-detect subjects from BIDS root and generate
    reproducible train/val/test splits.

    Returns a dict with:
        subjects   — all detected subjects
        train      — training subject IDs
        val        — validation subject IDs
        test       — test subject IDs
        seed       — random seed used
        ratios     — split ratios
        bids_root  — path used
    """
    bids_root = Path(bids_root)

    subject_dirs = sorted([
        d.name.replace("sub-", "")
        for d in bids_root.iterdir()
        if d.is_dir() and d.name.startswith("sub-")
    ])

    if not subject_dirs:
        raise RuntimeError(f"No subjects found in {bids_root}")

    assert abs(train_ratio + val_ratio + test_ratio - 1.0) < 1e-6, \
        "Ratios must sum to 1.0"

    rng = random.Random(seed)
    subjects = subject_dirs.copy()
    rng.shuffle(subjects)

    n = len(subjects)
    n_train = max(1, round(n * train_ratio))
    n_val   = max(1, round(n * val_ratio))
    n_test  = max(1, n - n_train - n_val)

    # Adjust if rounding causes issues
    while n_train + n_val + n_test > n:
        if n_test > 1:
            n_test -= 1
        elif n_val > 1:
            n_val -= 1
        else:
            n_train -= 1

    train = subjects[:n_train]
    val   = subjects[n_train:n_train + n_val]
    test  = subjects[n_train + n_val:n_train + n_val + n_test]

    splits = {
        "description": (
            "Reproducible train/val/test subject splits for NeuroBIDS-Flow benchmarking. "
            "Generated by src/neurobids_flow/splits.py"
        ),
        "bids_root": str(bids_root),
        "seed": seed,
        "ratios": {
            "train": train_ratio,
            "val": val_ratio,
            "test": test_ratio,
        },
        "n_subjects": n,
        "subjects": subjects,
        "train": train,
        "val": val,
        "test": test,
        "n_train": len(train),
        "n_val": len(val),
        "n_test": len(test),
    }

    return splits


def print_splits(splits: dict):
    print("\n" + "═" * 50)
    print("  NeuroBIDS-Flow — Subject Splits")
    print("═" * 50)
    print(f"  Total subjects : {splits['n_subjects']}")
    print(f"  Seed           : {splits['seed']}")
    print(f"  Ratios         : "
          f"train={splits['ratios']['train']:.0%}  "
          f"val={splits['ratios']['val']:.0%}  "
          f"test={splits['ratios']['test']:.0%}")
    print("─" * 50)
    print(f"  Train ({splits['n_train']})  : {splits['train']}")
    print(f"  Val   ({splits['n_val']})  : {splits['val']}")
    print(f"  Test  ({splits['n_test']})  : {splits['test']}")
    print("═" * 50)
    print()


def load_splits(path: str) -> dict:
    """Load splits from a saved JSON file."""
    with open(path) as f:
        return json.load(f)


def save_splits(splits: dict, path: str):
    """Save splits to a JSON file."""
    with open(path, "w") as f:
        json.dump(splits, f, indent=2)
    print(f"  Splits saved to: {path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="NeuroBIDS-Flow Train/Val/Test Splits Generator"
    )
    parser.add_argument("--bids-root", default="./bids_output")
    parser.add_argument("--train", type=float, default=0.6)
    parser.add_argument("--val", type=float, default=0.2)
    parser.add_argument("--test", type=float, default=0.2)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--save", type=str, default=None,
                        help="Path to save splits JSON (optional)")
    args = parser.parse_args()

    splits = generate_splits(
        bids_root=args.bids_root,
        train_ratio=args.train,
        val_ratio=args.val,
        test_ratio=args.test,
        seed=args.seed,
    )

    print_splits(splits)

    if args.save:
        save_splits(splits, args.save)
    else:
        # Auto-save to configs/splits.json
        default_path = Path("configs/splits.json")
        save_splits(splits, str(default_path))
        print(f"  Load with: from neurobids_flow.splits import load_splits")
        print(f"             splits = load_splits('configs/splits.json')")
        print()