"""
NeuroBIDS-Flow — Sample EEG Data Generator
===========================================
Generates one synthetic but valid EEG file per supported hardware format.
Files are ~60 seconds, 8 channels, with 20 events — suitable for ML evaluation.

Usage:
    python sample_data/generate_samples.py
"""

import os
import sys
import struct
import numpy as np
from pathlib import Path

# ── Output directory ──────────────────────────────────────────────────────────
OUT = Path(__file__).parent / "generated"
OUT.mkdir(parents=True, exist_ok=True)

# ── Shared EEG parameters ─────────────────────────────────────────────────────
SFREQ      = 256.0          # Hz
DURATION   = 60.0           # seconds — long enough for 20 events
N_SAMPLES  = int(SFREQ * DURATION)
N_CH       = 8
CH_NAMES   = ['Fp1','Fp2','C3','C4','P3','P4','O1','O2']
RNG        = np.random.default_rng(42)

# Event onsets — 20 events across 60 seconds (2 per class × 10 repetitions)
EVENT_ONSETS = [2.0, 5.0, 8.0, 11.0, 14.0, 17.0, 20.0, 23.0, 26.0, 29.0,
                32.0, 35.0, 38.0, 41.0, 44.0, 47.0, 50.0, 53.0, 56.0, 59.0]
EVENT_IDS    = [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2]


def make_eeg(n_ch=N_CH, n_samp=N_SAMPLES, sfreq=SFREQ, duration=DURATION):
    t   = np.linspace(0, duration, n_samp)
    eeg = RNG.normal(0, 15e-6, (n_ch, n_samp))
    eeg += 20e-6 * np.sin(2 * np.pi * 10 * t)
    eeg[-2] += 8e-6 * np.sin(2 * np.pi * 6 * t)
    eeg[-1] += 8e-6 * np.sin(2 * np.pi * 8 * t)
    return eeg


def sep(title):
    print(f"\n{'─'*60}")
    print(f"  {title}")
    print('─'*60)


# ─────────────────────────────────────────────────────────────────────────────
# 1. BrainProducts (.vhdr + .vmrk + .eeg)
# ─────────────────────────────────────────────────────────────────────────────
def gen_brainproducts():
    sep("1 / 5  BrainProducts  →  .vhdr + .vmrk + .eeg")
    try:
        import mne
        eeg  = make_eeg()
        info = mne.create_info(CH_NAMES, SFREQ, ch_types='eeg')
        raw  = mne.io.RawArray(eeg, info, verbose=False)

        onsets    = np.array(EVENT_ONSETS)
        durations = np.zeros(len(onsets))
        descs     = [f'S  {eid}' for eid in EVENT_IDS]
        raw.set_annotations(mne.Annotations(onsets, durations, descs))

        vhdr = OUT / 'sample_brainproducts.vhdr'
        raw.export(str(vhdr), fmt='brainvision', overwrite=True, verbose=False)
        print(f"  ✓  {vhdr.name}")
        print(f"  ✓  {vhdr.with_suffix('.vmrk').name}")
        print(f"  ✓  {vhdr.with_suffix('.eeg').name}")
        print(f"     Channels : {N_CH}  |  Duration : {DURATION}s  |  Fs : {SFREQ} Hz")
        print(f"     Events   : {len(EVENT_ONSETS)} events (S  1 × 10, S  2 × 10)")
    except ImportError as e:
        print(f"  ✗  Missing dependency: {e}")
    except Exception as e:
        print(f"  ✗  Error: {e}")


# ─────────────────────────────────────────────────────────────────────────────
# 2. Neuroscan (.cnt)
# ─────────────────────────────────────────────────────────────────────────────
def gen_neuroscan():
    sep("2 / 5  Neuroscan  →  .cnt")
    try:
        cnt_path = OUT / 'sample_neuroscan.cnt'
        eeg = make_eeg()
        with open(cnt_path, 'wb') as f:
            f.write(b'Version 3.0\x00' + b'\x00'*882)
            data_int = (eeg * 1e6 / 0.1).astype(np.int16)
            for s in range(N_SAMPLES):
                for c in range(N_CH):
                    f.write(struct.pack('<h', int(np.clip(data_int[c,s], -32768, 32767))))

        note = OUT / 'sample_neuroscan_note.txt'
        note.write_text(
            "NOTE: Genuine Neuroscan .cnt requires proprietary hardware.\n"
            "The plugin is validated via synthetic MNE RawArray in the test suite."
        )
        print(f"  ✓  {cnt_path.name}  (minimal binary — for plugin load testing)")
        print(f"     Channels : {N_CH}  |  Duration : {DURATION}s  |  Fs : {SFREQ} Hz")
    except Exception as e:
        print(f"  ✗  Error: {e}")


# ─────────────────────────────────────────────────────────────────────────────
# 3. OpenBCI (.txt)
# ─────────────────────────────────────────────────────────────────────────────
def gen_openbci():
    sep("3 / 5  OpenBCI Cyton  →  .txt")
    try:
        eeg    = make_eeg()
        path   = OUT / 'sample_openbci.txt'
        scale  = 0.02235
        counts = (eeg * 1e6 / scale).astype(int)

        event_col = np.zeros(N_SAMPLES, dtype=int)
        for onset, eid in zip(EVENT_ONSETS, EVENT_IDS):
            idx = int(onset * SFREQ)
            if idx < N_SAMPLES:
                event_col[idx] = eid

        with open(path, 'w') as f:
            f.write("%OpenBCI Raw EEG Data\n")
            f.write(f"%Number of channels = {N_CH}\n")
            f.write(f"%Sample Rate = {int(SFREQ)} Hz\n")
            f.write("%Board = OpenBCI_GUI$BoardShim\n")
            f.write("%Generated by NeuroBIDS-Flow sample generator\n")
            ch_cols = ', '.join([f'EXG Channel {i}' for i in range(N_CH)])
            f.write(f" Sample Index, {ch_cols}, Accel Channel 0, Accel Channel 1, "
                    f"Accel Channel 2, Other, Other, Other, Other, Other, Other, "
                    f"Other, Timestamp, Marker\n")
            for s in range(N_SAMPLES):
                ch_vals = ', '.join([f'{counts[c,s]:8d}' for c in range(N_CH)])
                marker  = f'{event_col[s]}' if event_col[s] > 0 else ''
                f.write(f"{s:6d}, {ch_vals}, "
                        f"0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "
                        f"{s/SFREQ:.6f}, {marker}\n")

        print(f"  ✓  {path.name}")
        print(f"     Channels : {N_CH}  |  Duration : {DURATION}s  |  Fs : {SFREQ} Hz")
        print(f"     Events   : {len(EVENT_ONSETS)} events in marker column")
    except Exception as e:
        print(f"  ✗  Error: {e}")


# ─────────────────────────────────────────────────────────────────────────────
# 4a. Muse (.csv — Mind Monitor format)
# ─────────────────────────────────────────────────────────────────────────────
def gen_muse_csv():
    sep("4a/ 5  Muse 2  →  .csv  (Mind Monitor format)")
    try:
        import csv
        eeg  = make_eeg(n_ch=4)
        path = OUT / 'sample_muse.csv'
        muse_chs = ['RAW_TP9','RAW_AF7','RAW_AF8','RAW_TP10']

        markers = [''] * N_SAMPLES
        for onset, eid in zip(EVENT_ONSETS, EVENT_IDS):
            idx = int(onset * SFREQ)
            if idx < N_SAMPLES:
                markers[idx] = f'stimulus_{6 if eid==1 else 8}hz'

        with open(path, 'w', newline='') as f:
            writer = csv.writer(f)
            writer.writerow(['TimeStamp'] + muse_chs +
                            ['Delta_TP9','Delta_AF7','Delta_AF8','Delta_TP10',
                             'Theta_TP9','Theta_AF7','Theta_AF8','Theta_TP10',
                             'Marker'])
            t0 = 1741872000.0
            for s in range(N_SAMPLES):
                ts  = t0 + s / SFREQ
                row = [f'{ts:.6f}'] + \
                      [f'{eeg[c,s]*1e6:.4f}' for c in range(4)] + \
                      ['0.0'] * 8 + [markers[s]]
                writer.writerow(row)

        print(f"  ✓  {path.name}")
        print(f"     Channels : TP9, AF7, AF8, TP10  |  Duration : {DURATION}s")
        print(f"     Events   : {len(EVENT_ONSETS)} events in Marker column")
    except Exception as e:
        print(f"  ✗  Error: {e}")


# ─────────────────────────────────────────────────────────────────────────────
# 4b. Muse (.xdf — MuseLSL / LabRecorder format)
# ─────────────────────────────────────────────────────────────────────────────
def gen_muse_xdf():
    sep("4b/ 5  Muse 2  →  .xdf  (MuseLSL / LabRecorder format)")
    try:
        path = OUT / 'sample_muse.xdf'
        eeg  = make_eeg(n_ch=4)
        muse_chs = ['TP9','AF7','AF8','TP10']
        t0   = 1741872000.0

        def xdf_bytes(tag, stream_id, content):
            payload = struct.pack('<I', stream_id) + content
            length  = len(payload)
            if length < 256:
                return (struct.pack('<H', tag) +
                        b'\x01' + struct.pack('B', length) + payload)
            else:
                return (struct.pack('<H', tag) +
                        b'\x04' + struct.pack('<I', length) + payload)

        ch_xml = ''.join(
            f'<channel><label>{c}</label><type>EEG</type><unit>microvolts</unit></channel>'
            for c in muse_chs)
        header_xml = (
            f'<?xml version="1.0"?><info>'
            f'<name>Muse</name><type>EEG</type>'
            f'<channel_count>4</channel_count>'
            f'<nominal_srate>{int(SFREQ)}</nominal_srate>'
            f'<channel_format>float32</channel_format>'
            f'<source_id>NeuroBIDS-Flow-Sample</source_id>'
            f'<desc><channels>{ch_xml}</channels></desc>'
            f'</info>'
        ).encode('utf-8')

        sample_bytes = b''
        for s in range(N_SAMPLES):
            ts = t0 + s / SFREQ
            sample_bytes += struct.pack('<d', ts)
            for c in range(4):
                sample_bytes += struct.pack('<f', float(eeg[c,s]*1e6))

        marker_xml = (
            '<?xml version="1.0"?><info>'
            '<name>Markers</name><type>Markers</type>'
            '<channel_count>1</channel_count>'
            '<nominal_srate>0</nominal_srate>'
            '<channel_format>string</channel_format>'
            '<source_id>NeuroBIDS-Flow-Markers</source_id>'
            '</info>'
        ).encode('utf-8')

        marker_bytes = b''
        for onset, eid in zip(EVENT_ONSETS, EVENT_IDS):
            ts    = t0 + onset
            label = f'stimulus_{6 if eid==1 else 8}hz'
            enc   = label.encode('utf-8')
            marker_bytes += struct.pack('<d', ts)
            marker_bytes += struct.pack('<I', len(enc)) + enc

        with open(path, 'wb') as f:
            f.write(b'\x89XDF\r\n\x1a\n')
            f.write(struct.pack('<H', 1) +
                    b'\x04' + struct.pack('<I', 4) +
                    b'<info><version>1.0</version></info>')
            f.write(xdf_bytes(2, 1, struct.pack('<I', len(header_xml)) + header_xml))
            f.write(xdf_bytes(2, 2, struct.pack('<I', len(marker_xml)) + marker_xml))
            n_enc = struct.pack('<I', N_SAMPLES)
            f.write(xdf_bytes(3, 1, n_enc + sample_bytes))
            f.write(xdf_bytes(3, 2, struct.pack('<I', len(EVENT_ONSETS)) + marker_bytes))
            for sid in [1, 2]:
                f.write(xdf_bytes(4, sid, struct.pack('<d', 0.0)))
                footer = b'<info><first_timestamp>0</first_timestamp></info>'
                f.write(xdf_bytes(6, sid, struct.pack('<I', len(footer)) + footer))

        print(f"  ✓  {path.name}")
        print(f"     Streams  : EEG (4ch, {int(SFREQ)} Hz) + Marker stream")
        print(f"     Duration : {DURATION}s  |  Events : {len(EVENT_ONSETS)}")
    except Exception as e:
        print(f"  ✗  Error: {e}")


# ─────────────────────────────────────────────────────────────────────────────
# 5. Emotiv EPOC+ (.edf)
# ─────────────────────────────────────────────────────────────────────────────
def gen_emotiv():
    sep("5 / 5  Emotiv EPOC+  →  .edf")
    try:
        import mne
        emotiv_chs = ['AF3','F7','F3','FC5','T7','P7','O1','O2']
        eeg  = make_eeg(n_ch=len(emotiv_chs))
        info = mne.create_info(emotiv_chs, SFREQ, ch_types='eeg')
        raw  = mne.io.RawArray(eeg, info, verbose=False)

        onsets    = np.array(EVENT_ONSETS)
        durations = np.zeros(len(onsets))
        descs     = [f'stimulus_{6 if eid==1 else 8}hz' for eid in EVENT_IDS]
        raw.set_annotations(mne.Annotations(onsets, durations, descs))

        path = OUT / 'sample_emotiv.edf'
        raw.export(str(path), fmt='edf', overwrite=True, verbose=False)
        print(f"  ✓  {path.name}")
        print(f"     Channels : {', '.join(emotiv_chs)}")
        print(f"     Duration : {DURATION}s  |  Fs : {SFREQ} Hz")
        print(f"     Events   : {len(EVENT_ONSETS)} EDF annotations")
    except ImportError as e:
        print(f"  ✗  Missing dependency: {e}")
    except Exception as e:
        print(f"  ✗  Error: {e}")


# ─────────────────────────────────────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────────────────────────────────────
if __name__ == '__main__':
    print(f"\n{'═'*60}")
    print("  NeuroBIDS-Flow — Sample EEG Data Generator")
    print(f"  Output directory: {OUT}")
    print(f"  Duration: {DURATION}s  |  Events per file: {len(EVENT_ONSETS)}")
    print(f"{'═'*60}")

    gen_brainproducts()
    gen_neuroscan()
    gen_openbci()
    gen_muse_csv()
    gen_muse_xdf()
    gen_emotiv()

    print(f"\n{'═'*60}")
    print("  All sample files generated successfully!")
    print(f"  Location: {OUT}")
    print(f"{'═'*60}\n")